# Generated by rust2rpm 25
%bcond_with check

%global crate hyprnome

Name:           hyprnome
Version:        0.2.0
Release:        %autorelease
Summary:        GNOME-like workspace switching in Hyprland

# FIXME: paste output of %%cargo_license_summary here
License:        GPL-3.0-or-later
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/donovanglover/hyprnome
Source:         %{url}/archive/%{version}/%{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gcc-c++

%global _description %{expand:
GNOME-like workspace switching in Hyprland.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -Dpm755 target/release/hyprnome %{buildroot}%{_bindir}/hyprnome
install -Dpm644 target/completions/_hyprnome %{buildroot}%{zsh_completions_dir}/_%{name}
install -Dpm644 target/completions/hyprnome.bash %{buildroot}%{bash_completions_dir}/%{name}
install -Dpm644 target/completions/hyprnome.fish %{buildroot}%{fish_completions_dir}/%{name}.fish
install -Dpm644 target/man/hyprnome.1 -t %{buildroot}%{_mandir}/man1

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc README.md
%{_bindir}/hyprnome
%{_mandir}/man1/hyprnome.1.*
%{bash_completions_dir}/%{name}
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}

%changelog
%autochangelog
