# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           rmpc
Version:        0.2.1
Release:        %autorelease
Summary:        Beautiful and configurable TUI client for MPD

License:        BSD-3-Clause
URL:            https://github.com/mierak/rmpc
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  gcc

%global _description %{expand:
A beautiful and configurable TUI client for MPD.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/rmpc

%changelog
%autochangelog
