# Generated by go2rpm 1.14.0
%bcond check 1

%global gomodulesmode GO111MODULE=on

# https://github.com/Aylur/ags
%global goipath         ags
%global forgeurl        https://github.com/Aylur/ags
Version:                2.3.0

%gometa -L -f

%global common_description %{expand:
Scaffoling CLI for Astal+TypeScript.}

Name:           aylurs-gtk-shell2
Release:        %autorelease
Summary:        Scaffoling CLI for Astal+TypeScript

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND GPL-3.0-only AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  pkgconfig(astal-gjs)

Requires:       astal-gjs%{?_isa}
Requires:       astal-libs%{?_isa}
Requires:       gtk4-layer-shell%{?_isa}

Supplements:    astal
Recommends:     astal-gtk4

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%define currentgoldflags %{shrink:-X ags/main.gtk4LayerShell=/usr/lib64/libgtk4-layer-shell.so.0
                          -X ags/main.astalGjs=$(pkg-config --variable=srcdir astal-gjs)}
%gobuild -o %{gobuilddir}/bin/ags %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%{gobuilddir}/bin/ags completion bash > %{name}.bash
%{gobuilddir}/bin/ags completion fish > %{name}.fish
%{gobuilddir}/bin/ags completion zsh > %{name}.zsh

install -Dpm0644 %{name}.bash %{buildroot}%{bash_completions_dir}/ags
install -Dpm0644 %{name}.fish %{buildroot}%{fish_completions_dir}/ags.fish
install -Dpm0644 %{name}.zsh  %{buildroot}%{zsh_completions_dir}/_ags

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs README.md
%{_bindir}/ags
%{bash_completions_dir}/ags
%{fish_completions_dir}/ags.fish
%{zsh_completions_dir}/_ags

%changelog
%autochangelog
